### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by icewuuu** [icewuuu/guest-house-booking-app#1]
- [ ] JWT + Passport.js role based authorization
- [ ] Automatic token renewal
- [ ] Email register verification
- [ ] Admin dashboard
- [ ]  Room booking system
